apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ska-dlm.fullname" . }}-rclone-configmap
data:
  rclone-start.sh: |-
    yes n | ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N '' || true
    eval "$(ssh-agent -s)"
    ssh-add /root/.ssh/id_rsa
    mkdir -p /shared-data/dlm/
    cp /root/.ssh/id_rsa.pub /shared-data/dlm/ 2>/dev/null 
    rclone \
    rcd \
    --rc-serve \
    --rc-addr \
    :5572 \
    --rc-no-auth \
    /